import { createApiEndpoints } from "@/stores/baseApi";

export interface Salary {
  _id: string;
  id?: string;
  staffId:
    | string
    | {
        _id: string;
        id?: string;
        name: string;
        email?: string;
        phone?: string;
        role: string;
      };
  amount: number;
  month: string; // YYYY-MM format (Gregorian)
  year: number; // Gregorian year
  paymentDate: string;
  status: "pending" | "paid";
  remarks?: string;
  createdBy:
    | string
    | {
        _id: string;
        id?: string;
        name: string;
        email?: string;
      };
  // Ethiopian calendar fields
  ethiopianMonth?: number;
  ethiopianYear?: number;
  ethiopianPaymentDate?: string;
  registeredDate?: string;
  salaryPeriod?: "monthly" | "per_month";
  // Withdrawal and payment tracking
  netAmount?: number;
  totalWithdrawals?: number;
  totalPayments?: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface SalaryListResponse {
  salaries: Salary[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    pages: number;
  };
}

export interface SalaryListQuery {
  staffId?: string;
  month?: string; // YYYY-MM format
  year?: number;
  status?: "pending" | "paid";
  page?: number;
  limit?: number;
}

export interface CreateSalaryInput {
  staffId: string;
  amount: number;
  month?: string; // YYYY-MM format (Gregorian) - auto-calculated
  year?: number; // Gregorian year - auto-calculated
  status?: "pending" | "paid";
  remarks?: string;
  clientId?: string; // For offline sync idempotency
  // Ethiopian calendar fields
  registeredDate: string; // YYYY-MM-DD (Ethiopian) - required
  paymentDate: string; // YYYY-MM-DD (Ethiopian) - required (payment due date)
  salaryPeriod?: "monthly" | "per_month";
}

export interface UpdateSalaryInput {
  amount?: number;
  status?: "pending" | "paid";
  paymentDate?: string; // ISO date string
  remarks?: string;
  ethiopianPaymentDate?: string;
  registeredDate?: string; // YYYY-MM-DD (Ethiopian)
  salaryPeriod?: "monthly" | "per_month";
}

export interface Withdrawal {
  _id?: string;
  id: string;
  salaryId: string;
  amount: number;
  reason:
    | "cash"
    | "broke_products"
    | "advance"
    | "deduction"
    | "loan"
    | "other";
  description?: string;
  createdAt: string;
  createdBy?: {
    _id: string;
    name: string;
    email?: string;
  };
}

export interface Payment {
  isAutoGenerated?: boolean;
  _id?: string;
  id: string;
  salaryId: string;
  amount: number;
  paymentDate: string;
  paymentMethod?: "cash" | "bank_transfer" | "check" | "mobile_money" | "other";
  remarks?: string;
  createdAt: string;
  createdBy?: {
    _id: string;
    name: string;
    email?: string;
  };
}

export interface CreateWithdrawalInput {
  amount: number;
  reason:
    | "cash"
    | "broke_products"
    | "advance"
    | "deduction"
    | "loan"
    | "other";
  description?: string;
}

export interface CreatePaymentInput {
  amount: number;
  paymentDate?: string; // ISO date string
  paymentMethod?: "cash" | "bank_transfer" | "check" | "mobile_money" | "other";
  remarks?: string;
}

export interface CountdownResponse {
  daysUntil: number;
  totalDays: number; // Total countdown period (30 days)
  nextPaymentDate: {
    ethiopian: string;
    gregorian: string;
  };
  registeredDate: string;
  registeredDateGregorian?: string;
  salaryPeriod?: "monthly" | "per_month";
}

export interface SalarySummaryResponse {
  summary: Array<{
    staffId: string;
    staffName: string;
    staffEmail?: string;
    staffPhone?: string;
    totalAmount: number;
    count: number;
    paidCount: number;
    pendingCount: number;
  }>;
  totals: {
    totalAmount: number;
    totalCount: number;
    totalPaid: number;
    totalPending: number;
  };
}

export const salaryApi = createApiEndpoints({
  endpoints: (build) => ({
    listSalaries: build.query<SalaryListResponse, SalaryListQuery | void>({
      query: (params) => {
        const queryParams = new URLSearchParams();
        if (params?.staffId) queryParams.append("staffId", params.staffId);
        if (params?.month) queryParams.append("month", params.month);
        if (params?.year) queryParams.append("year", params.year.toString());
        if (params?.status) queryParams.append("status", params.status);
        if (params?.page) queryParams.append("page", params.page.toString());
        if (params?.limit) queryParams.append("limit", params.limit.toString());

        const qs = queryParams.toString();
        return {
          url: `/salary${qs ? `?${qs}` : ""}`,
          method: "GET",
        };
      },
      transformResponse: (response: unknown): SalaryListResponse => {
        // API returns { success: true, data: { salaries: [], pagination: {...} } }
        const apiResponse = response as {
          success: boolean;
          data: SalaryListResponse;
        };
        return apiResponse.data;
      },
      providesTags: (result) =>
        result?.salaries
          ? [
              ...result.salaries.map((s) => ({
                type: "Salary" as const,
                id: s._id || s.id,
              })),
              { type: "Salary" as const, id: "LIST" },
            ]
          : [{ type: "Salary" as const, id: "LIST" }],
    }),

    getSalaryById: build.query<{ success: boolean; data: Salary }, string>({
      query: (id) => ({
        url: `/salary/${id}`,
        method: "GET",
      }),
      transformResponse: (response: unknown) => {
        const apiResponse = response as {
          success: boolean;
          data: Salary;
        };
        return apiResponse;
      },
      providesTags: (result, _error, id) => [{ type: "Salary" as const, id }],
    }),

    createSalary: build.mutation<
      { success: boolean; message: string; data: Salary },
      CreateSalaryInput
    >({
      query: (body) => ({
        url: "/salary",
        method: "POST",
        body,
      }),
      invalidatesTags: [{ type: "Salary", id: "LIST" }],
    }),

    updateSalary: build.mutation<
      { success: boolean; message: string; data: Salary },
      { id: string; data: UpdateSalaryInput }
    >({
      query: ({ id, data }) => ({
        url: `/salary/${id}`,
        method: "PATCH",
        body: data,
      }),
      invalidatesTags: (result, _error, { id }) => [
        { type: "Salary", id },
        { type: "Salary", id: "LIST" },
      ],
    }),

    deleteSalary: build.mutation<{ success: boolean; message: string }, string>(
      {
        query: (id) => ({
          url: `/salary/${id}`,
          method: "DELETE",
        }),
        invalidatesTags: (result, _error, id) => [
          { type: "Salary", id },
          { type: "Salary", id: "LIST" },
          { type: "Withdrawal" as const },
          { type: "Payment" as const },
        ],
      }
    ),

    getSalarySummary: build.query<
      { success: boolean; data: SalarySummaryResponse },
      { month?: string; year?: number }
    >({
      query: (params) => {
        const queryParams = new URLSearchParams();
        if (params?.month) queryParams.append("month", params.month);
        if (params?.year) queryParams.append("year", params.year.toString());

        const qs = queryParams.toString();
        return {
          url: `/salary/summary${qs ? `?${qs}` : ""}`,
          method: "GET",
        };
      },
      transformResponse: (response: unknown) => {
        const apiResponse = response as {
          success: boolean;
          data: SalarySummaryResponse;
        };
        return apiResponse;
      },
    }),

    getStaffSalaryHistory: build.query<
      { success: boolean; data: Salary[] },
      string
    >({
      query: (staffId) => ({
        url: `/salary/staff/${staffId}`,
        method: "GET",
      }),
      transformResponse: (response: unknown) => {
        const apiResponse = response as {
          success: boolean;
          data: Salary[];
        };
        return apiResponse;
      },
      providesTags: (result, _error, staffId) => [
        { type: "Salary" as const, id: `STAFF_${staffId}` },
      ],
    }),

    // Withdrawal endpoints
    listWithdrawals: build.query<
      { success: boolean; data: Withdrawal[] },
      string
    >({
      query: (salaryId) => ({
        url: `/salary/${salaryId}/withdrawals`,
        method: "GET",
      }),
      transformResponse: (response: unknown) => {
        const apiResponse = response as {
          success: boolean;
          data: Withdrawal[];
        };
        return apiResponse;
      },
      providesTags: (result, _error, salaryId) => [
        { type: "Salary" as const, id: salaryId },
        { type: "Withdrawal" as const, id: `SALARY_${salaryId}` },
      ],
    }),

    createWithdrawal: build.mutation<
      { success: boolean; message: string; data: Withdrawal },
      { salaryId: string; data: CreateWithdrawalInput }
    >({
      query: ({ salaryId, data }) => ({
        url: `/salary/${salaryId}/withdrawals`,
        method: "POST",
        body: data,
      }),
      invalidatesTags: (result, _error, { salaryId }) => [
        { type: "Salary", id: salaryId },
        { type: "Salary", id: "LIST" },
        { type: "Withdrawal", id: `SALARY_${salaryId}` },
      ],
    }),

    deleteWithdrawal: build.mutation<
      { success: boolean; message: string },
      { salaryId: string; withdrawalId: string }
    >({
      query: ({ salaryId, withdrawalId }) => ({
        url: `/salary/${salaryId}/withdrawals/${withdrawalId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, _error, { salaryId }) => [
        { type: "Salary", id: salaryId },
        { type: "Salary", id: "LIST" },
        { type: "Withdrawal", id: `SALARY_${salaryId}` },
      ],
    }),

    // Payment endpoints
    listPayments: build.query<{ success: boolean; data: Payment[] }, string>({
      query: (salaryId) => ({
        url: `/salary/${salaryId}/payments`,
        method: "GET",
      }),
      transformResponse: (response: unknown) => {
        const apiResponse = response as {
          success: boolean;
          data: Payment[];
        };
        return apiResponse;
      },
      providesTags: (result, _error, salaryId) => [
        { type: "Salary" as const, id: salaryId },
        { type: "Payment" as const, id: `SALARY_${salaryId}` },
      ],
    }),

    createPayment: build.mutation<
      { success: boolean; message: string; data: Payment },
      { salaryId: string; data: CreatePaymentInput }
    >({
      query: ({ salaryId, data }) => ({
        url: `/salary/${salaryId}/payments`,
        method: "POST",
        body: data,
      }),
      invalidatesTags: (result, _error, { salaryId }) => [
        { type: "Salary", id: salaryId },
        { type: "Salary", id: "LIST" },
        { type: "Payment", id: `SALARY_${salaryId}` },
      ],
    }),

    deletePayment: build.mutation<
      { success: boolean; message: string },
      { salaryId: string; paymentId: string }
    >({
      query: ({ salaryId, paymentId }) => ({
        url: `/salary/${salaryId}/payments/${paymentId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, _error, { salaryId }) => [
        { type: "Salary", id: salaryId },
        { type: "Salary", id: "LIST" },
        { type: "Payment", id: `SALARY_${salaryId}` },
      ],
    }),

    // Countdown endpoint
    getCountdown: build.query<
      { success: boolean; data: CountdownResponse },
      string
    >({
      query: (salaryId) => ({
        url: `/salary/${salaryId}/countdown`,
        method: "GET",
      }),
      transformResponse: (response: unknown) => {
        const apiResponse = response as {
          success: boolean;
          data: CountdownResponse;
        };
        return apiResponse;
      },
      providesTags: (result, _error, salaryId) => [
        { type: "Salary" as const, id: salaryId },
      ],
    }),

    // Net amount endpoint
    getNetAmount: build.query<
      { success: boolean; data: { netAmount: number } },
      string
    >({
      query: (salaryId) => ({
        url: `/salary/${salaryId}/net-amount`,
        method: "GET",
      }),
      transformResponse: (response: unknown) => {
        const apiResponse = response as {
          success: boolean;
          data: { netAmount: number };
        };
        return apiResponse;
      },
      providesTags: (result, _error, salaryId) => [
        { type: "Salary" as const, id: salaryId },
      ],
    }),
  }),
});

export const {
  useListSalariesQuery,
  useGetSalaryByIdQuery,
  useCreateSalaryMutation,
  useUpdateSalaryMutation,
  useDeleteSalaryMutation,
  useGetSalarySummaryQuery,
  useGetStaffSalaryHistoryQuery,
  useListWithdrawalsQuery,
  useCreateWithdrawalMutation,
  useDeleteWithdrawalMutation,
  useListPaymentsQuery,
  useCreatePaymentMutation,
  useDeletePaymentMutation,
  useGetCountdownQuery,
  useGetNetAmountQuery,
} = salaryApi;
